### ISSUE TITLE
Unable to verify signature on L1 hermeznetwork/geth-zkevm-contracts:v2.0.0-fork.5-geth1.13.1

### ISSUE THREAD

**Issue by zjg555543** [0xPolygon/supernets2-contracts#16]
**version:**
- https://github.com/0xPolygon/cdk-validium-node
- https://github.com/0xPolygon/cdk-validium-contracts
- https://github.com/0xPolygonHermez/zkevm-bridge-service.git v0.2.0
- L1 blockchain geth-zkevm-contracts:v2.0.0-fork.5-geth1.13.1

**steps:**
- redeploy the cdk-validium-contracts on the L1 chain**(geth-zkevm-contracts:v2.0.0-fork.5-geth1.13.1)**
- config sequencer-sender node config, 
   ```
        WaitPeriodSendSequence = "35s"
        LastBatchVirtualizationTimeMaxWaitPeriod = "20s"
        MaxBatchesForL1 = 2
  ```
- reconfiguration the contract and gen nums for the service, eg: sync/sequencer/bridge...
- send some txs on L2, make some batchs to trigger the **MaxBatchesForL1=2** condition
- the sequencer-sender will send batch tx error like this
![image](https://github.com/0xPolygonHermez/zkevm-contracts/assets/7919751/929c2260-2f59-49e7-978a-77526202ecd3)
- others: but if set MaxBatchesForL1 = 1, that is success.

**Comment by arnaubennassar** [comment]
The contracts that you're re-deploying are the exact same ones on `main` https://github.com/0xPolygon/cdk-validium-node?

**Comment by zjg555543** [comment]
> The contracts that you're re-deploying are the exact same ones on `main` https://github.com/0xPolygon/cdk-validium-node?

Yes. I write a docker-compose.yml for test the case.
Here is the build and run steps.
https://github.com/zjg555543/zkevm-docker/tree/zjg/validium#build

- here is the  [MaxBatchesForL1 = 2](https://github.com/zjg555543/zkevm-docker/blob/zjg/validium/config/test.node.config.toml#L102)  
- here is the [L1 image](https://github.com/zjg555543/zkevm-docker/blob/zjg/validium/docker-compose.yml#L185)

**Comment by zjg555543** [comment]
Geth L1 is not configured to produce blocks automatically, which makes sequencer fail because it's timestamp is ahead of L1. Add **--dev.period** like this.
```
 cdk-validium-mock-l1-network:
    container_name: cdk-validium-mock-l1-network
    image: hermeznetwork/geth-cdk-validium-contracts:v0.0.1
    ports:
      - 8545:8545
      - 8546:8546
    command:
      - "--http"
      - "--http.api"
      - "admin,eth,debug,miner,net,txpool,personal,web3"
      - "--http.addr"
      - "0.0.0.0"
      - "--http.corsdomain"
      - "*"
      - "--http.vhosts"
      - "*"
      - "--ws"
      - "--ws.origins"
      - "*"
      - "--ws.addr"
      - "0.0.0.0"
      - "--dev"
      - "--dev.period"
      - "1"
      - "--datadir"
      - "/geth_data"
      - "--syncmode"
      - "full"
      - "--rpc.allow-unprotected-txs"
```
